mybudget:
  app:
    mode: PROD
    dataBase:
      host: localhost
      dataBaseName: mybudget
      userName: postgres
      password: root
      maxConnection: 10
  graphite:
    activate: true
error:
  whitelabel:
    enabled: false
health:
  mongodb:
    enabled: false