mybudget:
  app:
    mode: DEV
    name: ${pom.name}
    version: ${pom.version}
    apiVersion: v1
    responseFormat: application/json;utf-8
    bugSnag: 980dc2bc1f03b3c7233c68707baf2cc6
    dataBase:
      host: localhost
      dataBaseName: mybudget
      userName: postgres
      password: root
      maxConnection: 10
  graphite:
    activate: false
    apiKey: c68abc3f-0356-4f5e-a0c3-062db5ae697b
    host: carbon.hostedgraphite.com
    port: 2003

error:
  whitelabel:
    enabled: false
health:
  mongodb:
    enabled: false
management:
  #port: -1 #ucomment to disable
  context-path: /manage
  security:
    role: MANAGER
info:
  build:
   artifact: ${project.artifactId}
   name: ${project.name}
   description: ${project.description}
   version: ${project.version}
endpoints:
  info:
    sensitive: true
  health:
    sensitive: true